# Generated by Django 5.0 on 2024-04-27 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('teste', 'TESTE'), ('teste1', 'TESTE1'), ('teste2', 'TESTE2')], default='', max_length=100)),
                ('descricao', models.TextField()),
                ('local', models.CharField(max_length=200)),
                ('publicada', models.BooleanField(default=True)),
                ('duracao', models.CharField(max_length=40)),
                ('data_publicada', models.DateTimeField(default=datetime.datetime.now)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
            ],
        ),
    ]
