# Generated by Django 5.0 on 2024-06-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0008_alter_estabelecimento_cep'),
        ('resumo', '0007_remove_resumo_sexo_resumo_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumo',
            name='estabelecimentos_favoritos',
            field=models.ManyToManyField(to='estabelecimentos.estabelecimento'),
        ),
    ]
