# Generated by Django 5.0 on 2024-06-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0008_alter_estabelecimento_cep'),
        ('resumo', '0010_remove_resumo_estabelecimentos_favoritos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumo',
            name='estabelecimentos_favoritos',
            field=models.ManyToManyField(null=True, related_name='estabelecimentos_favoritos', to='estabelecimentos.estabelecimento'),
        ),
        migrations.DeleteModel(
            name='EstabelecimentosFavoritos',
        ),
    ]
