# Generated by Django 5.0 on 2024-06-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumo', '0014_alter_resumo_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumo',
            name='idade',
            field=models.CharField(max_length=2),
        ),
    ]
