# Generated by Django 5.0 on 2024-06-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0008_alter_estabelecimento_cep'),
        ('resumo', '0016_remove_resumo_estabelecimentos_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumo',
            name='estabelecimentos_favoritos',
            field=models.ManyToManyField(null=True, related_name='estabelecimentos_favoritos', to='estabelecimentos.estabelecimento'),
        ),
    ]
