# Generated by Django 5.0 on 2024-08-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumo', '0020_alter_resumo_estabelecimentos_fav'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsFilterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='resumo',
            name='tags_filtro',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag_filter_user', to='resumo.tagsfilteruser'),
        ),
    ]
