# Generated by Django 4.2.4 on 2024-03-30 16:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('numero_telefone', models.CharField(max_length=20)),
                ('categoria', models.CharField(choices=[('teste', 'TESTE'), ('teste1', 'TESTE1'), ('teste2', 'TESTE2')], default='', max_length=100)),
                ('descricao', models.TextField()),
                ('local', models.CharField(max_length=200)),
                ('publicada', models.BooleanField(default=True)),
                ('data_publicada', models.DateTimeField(default=datetime.datetime.now)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
