# Generated by Django 5.0 on 2024-04-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimentos',
            name='usuario',
        ),
        migrations.AddField(
            model_name='estabelecimentos',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
