# Generated by Django 5.0 on 2024-04-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0003_rename_estabelecimentos_estabelecimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='numero_telefone',
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='avaliacao',
            field=models.FloatField(max_length=150, null=True),
        ),
    ]
