# Generated by Django 5.0 on 2024-04-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0004_remove_estabelecimento_numero_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='preco_medio',
            field=models.FloatField(default=0, max_length=120),
        ),
    ]
