# Generated by Django 5.0 on 2024-05-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0005_estabelecimento_preco_medio'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='cep',
            field=models.FloatField(default=0.0, max_length=120),
        ),
    ]
