# Generated by Django 5.0 on 2024-08-25 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0009_alter_estabelecimento_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='usuario_business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_business', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='categoria',
            field=models.CharField(choices=[('Árabe', 'ARABE'), ('Brasileira', 'BRASILEIRA'), ('Chinesa', 'CHINESA'), ('Italiana', 'ITALIANA'), ('Fast Food', 'FASTFOOD'), ('Gourmet', 'GOURMET'), ('Japonesa', 'JAPONESA'), ('Mexicana', 'MEXICANA'), ('Vegetariana', 'VEGETARIANA'), ('Vegana', 'VEGANA'), ('Pizza', 'PIZZA'), ('Sushi', 'SUSHI'), ('Frutos do mar', 'FRUTOSMAR'), ('Hambúrguer', 'HAMBURGUER'), ('Massa', 'MASSA'), ('Carne', 'CARNE'), ('Peixe', 'PEIXE'), ('Sopa', 'SOPA'), ('Salada', 'SALADA'), ('Sobremesa', 'SOBREMESSA')], default='', max_length=100),
        ),
    ]
