# Generated by Django 5.0 on 2024-08-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0010_estabelecimento_usuario_business_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('preco', models.FloatField(default=0.0, max_length=120)),
                ('serve', models.IntegerField(null=True)),
                ('imagem_produto', models.ImageField(blank=True, upload_to='fotos/produtos/%Y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='produtos',
            field=models.ManyToManyField(blank=True, null=True, related_name='produtos_adicionados', to='estabelecimentos.produtos'),
        ),
    ]
