# Generated by Django 5.0 on 2024-08-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0011_produtos_estabelecimento_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
