# Generated by Django 5.0 on 2024-08-28 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0012_produtos_disponivel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Produto',
        ),
    ]
