# Generated by Django 5.0 on 2024-12-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0015_estabelecimento_visualizacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='produtos',
            field=models.ManyToManyField(blank=True, related_name='produtos_adicionados', to='estabelecimentos.produto'),
        ),
    ]
