# Generated by Django 5.0 on 2025-05-09 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estabelecimentos', '0016_alter_estabelecimento_produtos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('idade', models.CharField(max_length=2)),
                ('orientacao_sexual', models.CharField(choices=[('LESBICA', 'Lésbica'), ('GAY', 'Gay'), ('BISSEXUAL', 'Bissexual'), ('TRANSGENERO', 'Transgênero'), ('NAO_BINARIO', 'Não-Binário'), ('HETEROSSEXUAL', 'Heterossexual'), ('OUTRO', 'Outro')], default='', max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('estabelecimentos_fav', models.ManyToManyField(blank=True, related_name='estabelecimentos_favoritos', to='estabelecimentos.estabelecimento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
