# Generated by Django 5.0 on 2024-04-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0002_remove_estabelecimentos_usuario_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estabelecimentos',
            new_name='Estabelecimento',
        ),
    ]
