# Generated by Django 5.0 on 2024-05-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0007_alter_estabelecimento_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='cep',
            field=models.IntegerField(default=0.0),
        ),
    ]
