# Generated by Django 5.0 on 2024-04-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumo',
            name='sexo',
            field=models.CharField(choices=[('Feminino', 'FEMININO'), ('Masculino', 'MASCULINO'), ('Outro', 'Outro')], default='', max_length=100),
        ),
    ]
