# Generated by Django 5.0 on 2024-06-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumo', '0006_alter_resumo_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumo',
            name='sexo',
        ),
        migrations.AddField(
            model_name='resumo',
            name='genero',
            field=models.CharField(choices=[('LESBICA', 'Lésbica'), ('GAY', 'Gay'), ('BISSEXUAL', 'Bissexual'), ('TRANSGENERO', 'Transgênero'), ('NAO_BINARIO', 'Não-Binário'), ('HETEROSSEXUAL', 'Heterossexual'), ('OUTRO', 'Outro')], default='', max_length=100),
        ),
    ]
