# Generated by Django 5.0 on 2024-06-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0008_alter_estabelecimento_cep'),
        ('resumo', '0008_resumo_estabelecimentos_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumo',
            name='estabelecimentos_favoritos',
            field=models.ManyToManyField(null=True, related_name='estabelecimentos_favoritos', to='estabelecimentos.estabelecimento'),
        ),
    ]
