# Generated by Django 5.0 on 2024-06-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0008_alter_estabelecimento_cep'),
        ('resumo', '0009_alter_resumo_estabelecimentos_favoritos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumo',
            name='estabelecimentos_favoritos',
        ),
        migrations.CreateModel(
            name='EstabelecimentosFavoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimentos_favoritos', models.ManyToManyField(null=True, related_name='estabelecimentos_favoritos', to='estabelecimentos.estabelecimento')),
            ],
        ),
    ]
