# Generated by Django 5.0 on 2024-06-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0008_alter_estabelecimento_cep'),
        ('resumo', '0011_resumo_estabelecimentos_favoritos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumo',
            name='estabelecimentos_favoritos',
            field=models.ManyToManyField(blank=True, related_name='estabelecimentos_favoritos', to='estabelecimentos.estabelecimento'),
        ),
    ]
