# Generated by Django 5.0 on 2024-06-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumo', '0012_alter_resumo_estabelecimentos_favoritos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumo',
            old_name='genero',
            new_name='orientacao_sexual',
        ),
    ]
