# Generated by Django 5.0 on 2024-06-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumo', '0013_rename_genero_resumo_orientacao_sexual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumo',
            name='idade',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
