# Generated by Django 5.0 on 2024-06-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumo', '0015_alter_resumo_idade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumo',
            name='estabelecimentos_favoritos',
        ),
    ]
