# Generated by Django 5.0 on 2024-06-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumo', '0018_alter_resumo_estabelecimentos_favoritos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumo',
            old_name='estabelecimentos_favoritos',
            new_name='estabelecimentos_fav',
        ),
    ]
