# Generated by Django 5.0 on 2024-06-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0008_alter_estabelecimento_cep'),
        ('resumo', '0019_rename_estabelecimentos_favoritos_resumo_estabelecimentos_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumo',
            name='estabelecimentos_fav',
            field=models.ManyToManyField(blank=True, null=True, related_name='estabelecimentos_favoritos', to='estabelecimentos.estabelecimento'),
        ),
    ]
