# Generated by Django 5.0 on 2024-08-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumo', '0022_alter_resumo_tags_filtro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumo',
            name='tags_filtro',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags_user', to='resumo.tagsfilteruser'),
        ),
    ]
