# Generated by Django 5.0 on 2024-12-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0016_alter_estabelecimento_produtos'),
        ('resumo', '0023_alter_resumo_tags_filtro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumo',
            name='estabelecimentos_fav',
            field=models.ManyToManyField(blank=True, related_name='estabelecimentos_favoritos', to='estabelecimentos.estabelecimento'),
        ),
        migrations.AlterField(
            model_name='resumo',
            name='tags_filtro',
            field=models.ManyToManyField(blank=True, related_name='tags_user', to='resumo.tagsfilteruser'),
        ),
    ]
